### ISSUE TITLE
How to deal with different licenses?

### ISSUE THREAD

**Issue by ways** [EURODEO/rodeo-edr-profile#21]
Should all data within a collection be required to have the same license?

**Comment by havardf** [comment]
It would be quite confusing for the user if they have to check every response for a license link in the case that some response superseeds the license in collection as a whole.

I would much prefer a rule like:
"A collection SHALL have a license (public domain or CC by 4). All data delivered as part of this collection is assumed to be under this license". @mrauhala @Teddy-1000 Is it possible to setup RODEO so that its one license pr. collection? Which would probably mean more than one collection for e-soh? If not, how should we advice the user how to handle this?

**Comment by Teddy-1000** [comment]
I think we can advise the implementer to split data in to several collection if the data in a collection have incompatible licenses, if all licenses are a form of free use, having the most restrictive one should suffice. We could also specify a data query dimension where you can select a list of licenses. 
For this profile, it is for RODEO, I suggest we assume most, if not all, data will be free to use.

**Comment by havardf** [comment]
I have another question related to this. Say we set a license of CC by 4 for the rodeo open data collections . This will then in some cases (like E-SOH) include data from many countries. How do we practically fulfill the requirements of attribution?  Asking people to attribute "Rodeo" does not make a lot of sense I think? Or do we need to list all institutes who supply data to the collection? 

This would be a lot easier if we release the data to the public domain (CC0), but I assume that is not really an option here.

**Comment by Teddy-1000** [comment]
In E-SOH all observations are required to provide the `naming_authority`, and can provide `creator_name`, `institution`. This metadata is attached to every observation. We could require this property to be included in all data replies.

**Comment by havardf** [comment]
Sounds doable. And in the end, it might be enough with an attribution to EUMETNET members or something like that. I will close this.
